services:
  - type: web
    name: arfi-proxy
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
